// frontendTest/vue-testing-demo/src/components/TodoApp/TodoHeader.vue
<template>
  <header class="header">
    <h1>todos</h1>
    <input
      class="new-todo"
      placeholder="What needs to be done?"
      autofocus
      data-testid="new-todo"
      @keyup.enter="handleNewTodo"
    />
  </header>
</template>

<script>
export default {
  name: "TodoHeader",
  methods: {
    handleNewTodo(e) {
      const value = e.target.value.trim();
      if (!value.length) {
        return;
      }
      this.$emit("new-todo", value);
      e.target.value = "";
    },
  },
};
</script>

// react/MobX6/mobx-guide/src/components/Todos/TodoHeader.js
import { useState } from "react"
import { useRootStore } from "../../stores/RootStore"

function TodoHeader() {
  const [title, setTitle] = useState("")
  const { todoListStore } = useRootStore()
  return (
    <header className="header">
      <h1>todos</h1>
      <input
        className="new-todo"
        placeholder="What needs to be done?"
        autoFocus
        value={title}
        onChange={event => setTitle(event.target.value)}
        onKeyUp={event => {
          if (event.key === "Enter") {
            todoListStore.createTodo(title)
            setTitle("")
          }
        }}
      />
    </header>
  )
}

export default TodoHeader
